### ISSUE TITLE
setup vue-tantan-stack

### ISSUE THREAD

**Issue by conceptual-phuc** [warpcgd/vue-tantan-stack#11]
Here is my setup:

![image](https://user-images.githubusercontent.com/43132460/53220044-1319dd80-3695-11e9-9ca1-90bc361e11ac.png)

But when running, i got this issue:
![image](https://user-images.githubusercontent.com/43132460/53220077-43617c00-3695-11e9-826b-9f00a97460e0.png)
![image](https://user-images.githubusercontent.com/43132460/53220089-4eb4a780-3695-11e9-8cee-fbbba8eb4afa.png)

How can i fix this?

**Comment by warpcgd** [comment]
-fix https://github.com/warpcgd/vue-tantan-stack/commit/e6eba1bb209a2a5a9890ebc403fe78450b4aa0ed
