### ISSUE TITLE
npm run dev 无法跑起来

### ISSUE THREAD

**Issue by hzfhhh** [warpcgd/vue-tantan-stack#4]
npm run dev 的时候报 ‘vue-tantan-stack-2.0\build\dev-server.js'错误，查看本地项目缺少build目录

**Comment by warpcgd** [comment]
@hzfhhh 你好，我还没有配置dev-server服务，目前只用到了webpack打包

**Comment by hzfhhh** [comment]
@warpcgd 多谢提醒
