### ISSUE TITLE
大佬，我又来啦，请教个事情～～～

### ISSUE THREAD

**Issue by meetflyings** [warpcgd/vue-tantan-stack#5]
手机端图片点击事件监听不到是因为堆叠效果么？如果想要点击事件打印出当前图片的src，该怎么做呢？Thanks

**Comment by warpcgd** [comment]
click事件在移动端监听不到的，需要自己模拟tap事件，或者用别人的tap插件，我的另一个项目里是自己实现的，你也可以在项目里touchend事件中加上这段
```
if (deltaTime < 300 && Math.abs(deltaX) < 10 && Math.abs(deltaY) < 10) {
          this.$emit('tap', this.basicdata)
}
```
详细可以看看[vue-concise-slider](https://github.com/warpcgd/vue-concise-slider/blob/master/src/components/slider.vue#L305)
